<?php

declare(strict_types=1);

// HR: Aplikacijske postavke koje HTML editor može mijenjati kroz administratorsko sučelje.
// EN: Application settings that the HTML editor may update through its administration UI.
return [
    'storage' => [
        'driver' => 'filesystem',
        'filesystem_path' => 'editor-html',
    ],
    'view' => [
        'table_of_contents' => false,
        'slug' => [
            'enabled' => false,
            'path' => 'view',
        ],
    ],
    'localization' => [
        'default_language' => 'hr',
    ],
    'uploads' => [
        'path' => 'editor-html/uploads',
        'max_size_mb' => 1024,
        'chunk_size_mb' => 1,
        'allowed_mime_types' => [
            'image/jpeg',
            'image/png',
            'image/gif',
            'image/webp',
            'application/pdf',
            'text/plain',
            'video/mp4',
            'video/webm',
            'application/zip',
            'application/x-zip-compressed',
            'application/rtf',
            'text/rtf',
            'application/msword',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
            'application/vnd.ms-word.document.macroenabled.12',
            'application/vnd.ms-word.template.macroenabled.12',
            'application/vnd.ms-excel',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
            'application/vnd.ms-excel.sheet.macroenabled.12',
            'application/vnd.ms-excel.template.macroenabled.12',
            'application/vnd.ms-excel.addin.macroenabled.12',
            'application/vnd.ms-excel.sheet.binary.macroenabled.12',
            'application/vnd.ms-powerpoint',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
            'application/vnd.openxmlformats-officedocument.presentationml.template',
            'application/vnd.openxmlformats-officedocument.presentationml.slide',
            'application/vnd.ms-powerpoint.presentation.macroenabled.12',
            'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
            'application/vnd.ms-powerpoint.template.macroenabled.12',
            'application/vnd.ms-powerpoint.slide.macroenabled.12',
            'application/vnd.ms-powerpoint.addin.macroenabled.12',
            'application/vnd.ms-project',
            'application/vnd.visio',
            'application/onenote',
            'application/vnd.ms-works',
            'application/vnd.ms-xpsdocument',
            'application/vnd.ms-publisher',
            'application/x-mspublisher',
            'application/vnd.ms-access',
            'application/x-msaccess',
            'application/vnd.ms-outlook',
            'application/vnd.ms-office',
            'message/rfc822',
            'application/vnd.oasis.opendocument.base',
            'application/vnd.oasis.opendocument.text',
            'application/vnd.oasis.opendocument.text-template',
            'application/vnd.oasis.opendocument.text-master',
            'application/vnd.oasis.opendocument.text-master-template',
            'application/vnd.oasis.opendocument.text-web',
            'application/vnd.oasis.opendocument.spreadsheet',
            'application/vnd.oasis.opendocument.spreadsheet-template',
            'application/vnd.oasis.opendocument.presentation',
            'application/vnd.oasis.opendocument.presentation-template',
            'application/vnd.oasis.opendocument.graphics',
            'application/vnd.oasis.opendocument.graphics-template',
            'application/vnd.oasis.opendocument.formula',
            'application/vnd.oasis.opendocument.formula-template',
            'application/vnd.oasis.opendocument.database',
            'application/vnd.oasis.opendocument.chart',
            'application/vnd.oasis.opendocument.chart-template',
            'application/vnd.oasis.opendocument.image',
            'application/vnd.oasis.opendocument.image-template',
            'application/vnd.sun.xml.writer',
            'application/vnd.sun.xml.writer.template',
            'application/vnd.sun.xml.writer.global',
            'application/vnd.sun.xml.calc',
            'application/vnd.sun.xml.calc.template',
            'application/vnd.sun.xml.draw',
            'application/vnd.sun.xml.draw.template',
            'application/vnd.sun.xml.impress',
            'application/vnd.sun.xml.impress.template',
            'application/vnd.sun.xml.math',
            'image/tiff',
            'image/bmp',
            'video/x-msvideo',
            'video/x-matroska',
            'audio/mp4',
            'audio/mpeg',
            'text/csv',
            'text/calendar',
            'application/gzip',
            'application/epub+zip',
        ],
    ],
];
